-- Migration 020 — profiles.dashboard_video_id
--
-- Holds the Heygen video_id of a per-user personalised dashboard hero
-- video ("Hi {first_name}, welcome to InvestorPilot…"). Lazily generated
-- on the user's first dashboard visit by /api/dashboard/heygen-video.
--
-- Null means: no personal video yet (or generation failed and was cleared).
-- The endpoint falls back to the org-wide HEYGEN_VIDEO_ID env var so the
-- hero always has something to show.
--
-- Idempotent.
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS dashboard_video_id TEXT;
